name: 'gh-action-postdoc'
description: 'Documentation generator'
author: 'cnheider'

branding:
  icon: 'book'
  color: 'red'

inputs:
  documentation_path:
    description: 'path to the sphinx documentation source root.'
    required: false
    default: "docs/"

  output_type:
    description: 'The output type of the sphinx documentation'
    required: false
    default: html

  branch:
    description: 'Destination branch to push changes'
    required: false
    default: 'master'

runs:
  using: 'docker'
  image: 'Dockerfile'
